package Controller.CGL;

import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Date;

import Controller.MyCalendar;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;


public class FirstPdf {
	private static String FILE = "c:/temp/FirstPdf.pdf";
	
	private static Font Garamond = new Font(Font.FontFamily.HELVETICA, 18,
			Font.BOLD ,BaseColor.GRAY);
	private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
			Font.NORMAL, BaseColor.RED);
	private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
			Font.BOLD);
	private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
			Font.BOLD);
	
	

	public void pdfCreator(String FILE) {
		try {
			Document document = new Document();
			PdfWriter.getInstance(document, new FileOutputStream(FILE));
			document.open();
			addMetaData(document);
			addTitlePage(document);
			
			document.close();
		} catch (Exception e) {
			e.printStackTrace();
		}
	
	}
	
	private static void addMetaData(Document document) {
		document.addTitle("Event Name");
		document.addSubject("Payment Notification");
		document.addKeywords("Payment,GR Administrator");
		document.addAuthor("GR Administrator");
		document.addCreator("GR Administrator");
	}

	private static void addTitlePage(Document document)
			throws DocumentException, MalformedURLException, IOException {
		
		Image image = Image.getInstance("src\\images\\CGL\\Reunion.jpg");
		image.setAbsolutePosition(80f, 700f);
		image.scaleAbsolute(400f, 150f);
		document.add(image);
		Paragraph preface = new Paragraph();
		// We add 6 empty line
		addEmptyLine(preface, 6);
		// Lets write a big header
		Paragraph paragraph = new Paragraph("Payment Notification",Garamond);
		paragraph.setIndentationLeft(150f);
		preface.add(paragraph);
		addEmptyLine(preface, 1);
		preface.add(new Chunk("Event Name:                         "));
        preface.add(new Chunk("No Of Guests: "));
        addEmptyLine(preface, 1);
        preface.add(new Chunk("Event Date:                         "));
        preface.add(new Chunk("Event Time: "));
        addEmptyLine(preface, 1);
        preface.add(new Chunk("Location:                         "));
        preface.add(new Chunk("Ballroom: "));
        addEmptyLine(preface, 1);
        preface.add(new Paragraph("Event Description: "));
 		addEmptyLine(preface,1);
        addEmptyLine(preface, 1);
		preface.add(new Paragraph("****************************************************************************************************************"));
		Paragraph paragraph1 = new Paragraph("Payment Details",Garamond);
		paragraph1.setIndentationLeft(170f);
		preface.add(paragraph1);
		addEmptyLine(preface, 1);
		preface.add(new Paragraph("Total Ballroom Price : $"));
		addEmptyLine(preface,1);
		preface.add(new Paragraph("Total Entertainment Price : $"));
		addEmptyLine(preface,1);
		preface.add(new Paragraph("Total Meal Price : $"));
		addEmptyLine(preface,1);
		preface.add(new Paragraph("Package Discount: $"));
		addEmptyLine(preface,1);
		preface.add(new Paragraph("Total Price :$"));
		addEmptyLine(preface, 2);
		preface.add(new Paragraph("Please make your first payment(50% of total Price) Of $200 as soon as possible :",smallBold));
		addEmptyLine(preface,1);
		preface.add(new Paragraph("****************************************************************************************************************"));
	 	// Will create: Report generated by: _name, _date
		preface.add(new Paragraph("Payment Notification generated by: " + System.getProperty("user.name") + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
		smallBold));
		addEmptyLine(preface, 1);
		preface.add(new Paragraph("Terms & Conditions: Once payment is made,there will be no refund .",
		redFont));
		document.add(preface);
		// Start a new page
		document.newPage();
	}

	private static void addEmptyLine(Paragraph paragraph, int number) {
		for (int i = 0; i < number; i++) {
			paragraph.add(new Paragraph(" "));
		}
	}
	
	public static void main(String args[]){
		FirstPdf f1 = new FirstPdf();
		f1.pdfCreator(FILE);
	}
} 